//
// Created by floris on 4/12/17.
//

#define INTEGER_READ_CALL_NUMBER 5u
#define CHARACTER_READ_CALL_NUMBER 12u
#define STRING_READ_CALL_NUMBER 12u
#define INTEGER_WRITE_CALL_NUMBER 1u
#define CHARACTER_WRITE_CALL_NUMBER 11u
#define STRING_WRITE_CALL_NUMBER 4u


#include "Type.h"

Type& Type::NUMERIC = *(new PrimitiveType(INTEGER_READ_CALL_NUMBER, INTEGER_WRITE_CALL_NUMBER));
Type& Type::CHARACTER = *(new PrimitiveType(CHARACTER_READ_CALL_NUMBER, CHARACTER_WRITE_CALL_NUMBER));
Type& Type::BOOLEAN = *(new PrimitiveType(INTEGER_READ_CALL_NUMBER, INTEGER_WRITE_CALL_NUMBER));
Type& Type::STRING = *(new PrimitiveType(STRING_READ_CALL_NUMBER, STRING_WRITE_CALL_NUMBER));
